### ISSUE TITLE
The engine "node" is incompatible with this module. Expected version ">= 6.9.5"

### ISSUE THREAD

**Issue by kmamykin** [leandrowd/react-easy-swipe#13]
When installing `react-responsive-carousel` I am getting an error from yarn and the package does not install because of this dependency has a higher requirement for node. 

```
$ yarn add react-responsive-carousel
yarn add v0.23.2
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error react-easy-swipe@0.0.10: The engine "node" is incompatible with this module. Expected version ">= 6.9.5".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

The question is: is it really necessary? I don't really want to change the version of node...

**Comment by leandrowd** [comment]
Minimum for yarn is node 6. Feel free to change it in the package.json.
Shouldn't be an issue. However, I need to ask, why are you not using a node
version manager like nvm? It would make your life so much easier whenever
you need to change versions.

**Comment by kmamykin** [comment]
Whether or not I use nvm is besides the point (and I do use it). 

I am merely pointing out that yarn now refuses to install this module (and any module which has this as a dependency) and node version < 6.9.5, and that requirement is unnecessary, or at least can be lowered to require node > 6.0.0.

**Comment by leandrowd** [comment]
Version was changed to > 6. Hope it helps.

**Comment by v3rron** [comment]
I'm using Meteor, which unfortunately still uses node 4 as a dependency.
When running `meteor yarn`, I get an error that this package is incompatible with node 4.
It makes this package unusable to whole Meteor community.
I don't think node 6 engine dependency is necessary for this package.
