### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "transform-es2015-modules-umd"

### ISSUE THREAD

**Issue by murraysmart** [leandrowd/react-easy-swipe#19]
If I do a **npm install** on a project that lists "react-easy-swipe" as a dependency, **npm run build** fails with:
```js
ERROR in ./~/react-easy-swipe/lib/index.js
Module build failed: ReferenceError: Unknown plugin "transform-es2015-modules-umd" specified in "C:\\Project\\node_modules\\react-easy-swipe\\.babelrc"
```

Manually deleting the .babelrc file inside `node_modules/react-easy-swipe/` does serve as a work-around so this isn't strictly speaking a blocking issue.

I believe a similar error was experienced in the following project, which outlines how they managed to resolve it by not publishing the .babelrc file to npm.

https://github.com/developit/preact-redux/issues/19

**Comment by trevorgk** [comment]
I am experiencing this as well.

@murraysmart the solution you provided worked for me

**Comment by AmolST** [comment]
Even I am facing same issue.

**Comment by leandrowd** [comment]
I ignored the .babelrc file on .npmignore. Last published version should have this fixed.
