### ISSUE TITLE
Move React to devDependencies.

### ISSUE THREAD

**Issue by gianlucacandiotti** [leandrowd/react-easy-swipe#2]
Could you move react to devDependencies? I'm using react 0.14.7 and if I try installing this package it crashes and tells me it couldn't install the dependency and somehow react gets erased from my node_modules. Since it's a React Component, can't we just let it be an implicit dependency?

**Comment by leandrowd** [comment]
Sounds reasonable enough. Can you send a PR? Otherwise I can do it later...

**Comment by gianlucacandiotti** [comment]
Sure, I'll send one. Thanks!
