### ISSUE TITLE
[NOT ISSUE] - Adding threshold to onSwipeDirection? 

### ISSUE THREAD

**Issue by 24dev** [leandrowd/react-easy-swipe#23]
Is it possible to add a threshold value to a onSwipeRight? 

Or do we need to use onSwipeMove and then have a conditional to achieve the same effect?

Many thanks, great package!

**Comment by kirill-konshin** [comment]
I have a `react-slick` gallery and I am using up/down swipes of `react-easy-swipe` to switch between carousels (there are many of them on page). When user swipes diagonally both swipe handlers react on the gesture.

**Comment by kirill-konshin** [comment]
So far I found the following solution:

```js
class ArticlesSliderComponent extends Component {

    position = {x:0, y:0};

    handleScrollDebounced = (e) => { ... };

    checkThreshold = () => {
        return Math.abs(this.position.x) < 50;
    };

    onSwipeMove = (position) => {
        this.position = position;
        return true;
    };

    onSwipeUp = () => {
        if (!this.checkThreshold()) return;
        this.handleScrollDebounced({deltaY: 1});
    };

    onSwipeDown = () => {
        if (!this.checkThreshold()) return;
        this.handleScrollDebounced({deltaY: -1});
    };

    render() {
        return (
            <Swipe
                onSwipeMove={this.onSwipeMove}
                onSwipeUp={this.onSwipeUp}
                onSwipeDown={this.onSwipeDown}>
                ...stuff
            </Swipe>
        );

    }
}
```

Not using state because it's internal temp var and state is updated in handlers.

**Comment by vabhishek-me** [comment]
I solved it by using the tolerance prop.

**Comment by jacksonkr** [comment]
> I solved it by using the tolerance prop.

@vabhishek-me What did this look like? I'm also stuck on reading the swipe direction from the event - not sure if it's possible other than doing the logic manually which defeats the purpose of me using a library.

**Comment by vabhishek-me** [comment]
@jacksonkr Not sure about how to read the direction, but using `tolerance` prop, you can specify after how much pixel should the event be triggerd.

**Comment by jacksonkr** [comment]
> @jacksonkr Not sure about how to read the direction, but using `tolerance` prop, you can specify after how much pixel should the event be triggerd.

Do you have code you can show me? I searched the readme and found nothing on "tolerence"

**Comment by vabhishek-me** [comment]
Check out this PR: #38 

You can use it like this
```jsx
<Swipe onSwipeLeft={onRightSlide} onSwipeRight={onLeftSlide} tolerance={100}>
  /* your slider or div */
</Swipe>
```

this will only call `onSwipeLeft` and `onSwipeRight` only if the swipe has covered atleast 100 pixels.
