### ISSUE TITLE
If component is wrapped with `react-contextmenu`, swipe events don't work properly

### ISSUE THREAD

**Issue by kunokdev** [leandrowd/react-easy-swipe#28]
I wrapped my whole layout like so:

```jsx
<Swipe
    onSwipeLeft={() => this.handleSwipe('left')}
    onSwipeRight={() => this.handleSwipe('right')}
>
      <MYLAYOUT />
</Swipe>
```

### GOOD BEHAVIOR 
Anywhere I swipe I get nice events. If I would have used `onSwipeMove` prop instead, it would call its handle function for every position change.

### BAD BEHAVIOR
However, neither of these works if component over which swipe happened is wrapped with component from library `react-contextmenu`. Only start and end events would be triggered. 
What could be causing this issue? `react-contextmenu` is lib for adding right click functionality to the component. 
I can provide minimal demo if needed for further investigation.

**Comment by leandrowd** [comment]
It means that the library `react-contextmenu` probably has an event handler that catches the touch and calls `event.stopPropagation()` on it. This would make impossible for any other library to handle it...

**Comment by leandrowd** [comment]
Just had a quick look at their codebase. This line seems to be the cause of your issues: https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenuTrigger.js#L65

**Comment by kunokdev** [comment]
Thanks for such a quick reply. I will think further what is the best solution to resolve this. I will post it here upon then.

**Comment by leandrowd** [comment]
Yeah, that would be great. I recommend you opening an issue there and asking them for a solution. Maybe they can add a prop that let's you decide if it needs to stop propagation or not.

**Comment by kunokdev** [comment]
@leandrowd That's what I am going to do.
