### ISSUE TITLE
Binding function to this??

### ISSUE THREAD

**Issue by jonnydungeons** [leandrowd/react-easy-swipe#30]
I need to be able to access the context and thus I am trying to bind my function to "this". In the swipe component how can I do this. I need to be able to access state and setState, some pretty common objects within react components. Here is a piece of incomplete code below:

class Carousel extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      count: 3,
      current: 0,
      active: 0
    };

    this.onSwipeLeft = this.onSwipeLeft.bind(this);
    this.onSwipeRight = this.onSwipeRight.bind(this);
  }

slide(i) {
    this.setState(...this.state,{ active: i});
  }

onSwipeLeft(event) {

    console.log('Swipe left...', event);
    console.log('this', parseInt(this.children.key) + 1);
    this.slide(parseInt(this.children.key) + 1);
  }

**Comment by leandrowd** [comment]
State is private to a component and you won't be able to access it. You need to use the API provided. For instance, if you pass an "onSwipeLeft" prop to the slider, it will be called with the current item... Check the examples and let me know how it goes...

**Comment by jonnydungeons** [comment]
I was able to pass in a function with no arguments to each of your onSwipeLeft and onSwipeRight and able to access context this way.

**Comment by leandrowd** [comment]
It's javascript so you might be able to hack anything out of it. However, I don't recommend it if you are writing anything serious or if you want other people to maintain the code you are writing.

Also, if you do it that way and I change something, your app might break. I can't ensure that the internals of the code will be backwards compatible. 
On the other hand, if you use the exposed API (props), then it's much easier for me to avoid breaking it, and for you to maintain.

**Comment by jonnydungeons** [comment]
@leandrowd - Thanks for getting back to me.

**Comment by liesahead** [comment]
@J0NNYZER0 , it's pretty easy. Let's say

```jsx
class Carousel extends React.Component {
    state = {
        count: 3,
        current: 0,
        active: 0,
    };

    onSwipeLeft = () => {
        this.setState({
            active: 5,
        });
    }

    render() {
        <Swipe onSwipeLeft={ this.onSwipeLeft }>{ children }</Swipe>
    }
}
```
