### ISSUE TITLE
Swipe Top triggered when swiping right

### ISSUE THREAD

**Issue by leotorres-16** [leandrowd/react-easy-swipe#34]
Hi,

I am trying to use this component, I used the onSwipeLeft and onSwipeRight commands and it works well, but then I saw a weird behavior, when I swiped up or down it will still trigger left and right. Is there any way to make it only trigger when swiping left or right?

Thanks a lot for your help

**Comment by shivatinu** [comment]
Even I encountered the same problem, but there seems to be no issue with the code (but the documentation). After I went through the code, found a prop `tolerance` which has to be passed to correct this. 

Try something like below,

    <Swipe onSwipeLeft = { this.onSwipeLeft.bind(this) }
           onSwipeRight = { this.onSwipeRight.bind(this) }
           tolerance = { 100 }>
    </Swipe>

Adjust the tolerance value per your needs. Hope this helps !

**Comment by guacjack** [comment]
@shivatinu This also worked for me. Cheers mate.

**Comment by kkuzmina** [comment]
@shivatinu Thank you!!

**Comment by keithpickering** [comment]
Thanks @shivatinu! This really should be in the docs, but it definitely saved a bit of time I would've spent comparing the values myself.
