### ISSUE TITLE
Custom components for Swipe container

### ISSUE THREAD

**Issue by frankcortes** [leandrowd/react-easy-swipe#37]
Currently, we can customize the `tagname` attribute of our swipe component, which is nice. Nevertheless, this only works for react native components like `div` or `li`. If only [this rule](https://github.com/leandrowd/react-easy-swipe/blob/master/src/react-swipe.js#L39) could be modified and it could accept also react components instead of strings, we could add the swipe functionality to our custom awesome components. 
Also that could be remove [this side effect](https://reactjs.org/blog/2017/09/08/dom-attributes-in-react-16.html) , because this library is adding their attributes to a native `div` component by default, so react easy swipe is generating a `div` with `onSwipeLeft`, `tolerance`, etc. as DOM attributes, which is throwing a lot of warnings.

**Comment by leandrowd** [comment]
@frankcortes, that's a great idea. Would you be able to prepare a PR?
