### ISSUE TITLE
Component doesn't swipe when wrapped with <Swipe>

### ISSUE THREAD

**Issue by SavedByZero** [leandrowd/react-easy-swipe#54]
Hi there,

My render looks like this: 
```
 return (<Swipe >
          <div className="screen" >        
          <div  className="bg2" style={{height: newPageHeight+"px"}}>         
             
</div>
        <div className="screendimmer1" >
</div>
        <div className="image23" style={{top: infoButtonTopValue+"px"}} onClick={this.showPopup}></div>
        <div className="answers" style={{ top: "291.00px"}}>{
                choices.map( (item, index) =>{
                        return (<Answer key={index} returnAnswer={this.returnAnswer} item={item} index={index} totalCount={choices.length} />)
                }

                )
        }            
</div>
        <div className="question">{this.props.questionText}</div>
        <div className={"iconavatarplaceholder "+this.props.avatarClass} style={{top:avatarIconTopValue+"px"}}></div>

        <div className={"popup " + visibilityClass}>            
			<div  className={"screendimmer1 " + visibilityClass}>                
				<div className="rectangle12"></div>
			</div>
            <div  className={"rectangle20 " + visibilityClass}></div>
            <div className={"popuptext " + visibilityClass}>{this.props.popupInfo}</div>
            <div  className={"closex " + visibilityClass} onClick={this.hidePopup}></div>
		</div>
</div>
</Swipe>);
```

I have installed the component and imported it up top as per the documentation.  However, the component does not swipe away when I try to swipe it left or right from my iphone 12 while running it on localhost.  

Edit: The *events* work when I attach them.  However, the component doesn't actually swipe left or right.

**Comment by desmukh** [comment]
In order to get the Swipe component to respond, you'll need to include the props to tell to it what to do when it is swiped. See the example from the documentation, which calls different functions when the onSwipeStart, onSwipeMove, etc events are triggered:

`
<Swipe
  onSwipeStart={this.onSwipeStart}
  onSwipeMove={this.onSwipeMove}
  onSwipeEnd={this.onSwipeEnd}>
    <div style={boxStyle}>Open the console and swipe me</div>
</Swipe>
`
