### ISSUE TITLE
target

### ISSUE THREAD

**Issue by Yuriy1988** [leandrowd/react-easy-swipe#7]
How can I get event.target onSwipeLeft (for example)?
I have to handle swipes depends on targets in my project.

**Comment by leandrowd** [comment]
I expect the swiper to be a wrapper agnostic of its content. Ideally, you would have a parent component or container handling its children state. In this case, all that matters is the direction (up, down, right, left) or the amount of pixels swiped in a movement (swipeMove).

Would you like to provide an example of what you want to accomplish so we can discuss if the target is really needed?

**Comment by Yuriy1988** [comment]
I'm developing app for browser using react and for mobile using react-native with webView;
On mobile i have sidebar, so when i swipe right on the screen - i expect sidebar to be open.
And when i swipe left sidebar should be closed; 
But also I have videos with progress bars on my main screen and when i swipe on videos i expect that sidebar will opens,
and if i swipe on video's progress bar i don't wont sidebar to be opened, i just want to interact with progress bar;
So thats why i need target to handle swipes  properly :)

**Comment by leandrowd** [comment]
Hi @Yuriy1988, I've update the callbacks to get the event as second argument. It was published to [npm](https://www.npmjs.com/package/react-easy-swipe) as v0.0.7.

Please update your version and let me know how it goes :)
