### ISSUE TITLE
Can we add mouse support?

### ISSUE THREAD

**Issue by AlastairTaft** [leandrowd/react-easy-swipe#8]
This package is really useful, but it would be great if the swipe also worked on desktop too.

**Comment by leandrowd** [comment]
I don't see any harm in having the mouse behaviour being handled if we hide it behind a prop and keep it disabled by default. Would you be interested in implement it?

**Comment by leandrowd** [comment]
You got lucky! I just added support to mouse events. 

Please update to the latest version from npm and pass a prop `allowMouseEvents`.

**Comment by AlastairTaft** [comment]
That's awesome! Thank you
